CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                          NVARCHAR (450)     NOT NULL,
    [UserName]                    NVARCHAR (256)     NULL,
    [NormalizedUserName]          NVARCHAR (256)     NULL,
    [Email]                       NVARCHAR (256)     NULL,
    [EmailKey]                    INT                IDENTITY(1,1) NOT NULL, -- New column for email incremental key
    [NormalizedEmail]             NVARCHAR (256)     NULL,
    [EmailConfirmed]              BIT                NOT NULL,
    [PasswordHash]                NVARCHAR (MAX)     NULL,
    [SecurityStamp]               NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]            NVARCHAR (MAX)     NULL,
    [PhoneNumber]                 NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed]        BIT                NOT NULL,
    [TwoFactorEnabled]            BIT                NOT NULL,
    [LockoutEnd]                  DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]              BIT                NOT NULL,
    [AccessFailedCount]           INT                NOT NULL,
    [OldId]                       INT                NOT NULL,
    [OldLogin]                    NVARCHAR (MAX)     NULL,
    [OldPassword]                 NVARCHAR (MAX)     NULL,
    [FirstName]                   NVARCHAR (MAX)     NULL,
    [LastName]                    NVARCHAR (MAX)     NULL,
    [AltPhone]                    NVARCHAR (MAX)     NULL,
    [Address]                     NVARCHAR (MAX)     NULL,
    [City]                        NVARCHAR (MAX)     NULL,
    [State]                       NVARCHAR (MAX)     NULL,
    [Zip]                         NVARCHAR (MAX)     NULL,
    [DateOfBirth]                 DATE               NULL,
    [OldSiteId]                   INT                NOT NULL,
    [OldType]                     INT                DEFAULT ((54)) NOT NULL,
    [Gender]                      NVARCHAR (1)       NOT NULL,
    [TravelTime]                  NVARCHAR (MAX)     NULL,
    [JoinDate]                    DATE               NULL,
    [OldSponsoredById]            INT                NOT NULL,
    [SponsoredById]               NVARCHAR (450)     NULL,
    [OldAuthLevel]                INT                NOT NULL,
    [Active]                      BIT                NOT NULL,
    [DeactiveCause]               NVARCHAR (MAX)     NULL,
    [BranchId]                    INT                NOT NULL,
    [OldStatus]                   INT                NOT NULL,
    [Medical]                     INT                NOT NULL,
    [DateInjured]                 DATE               NULL,
    [ReleaseSigned]               BIT                NOT NULL,
    [LiabilitySigned]             BIT                NOT NULL,
    [Comments]                    NVARCHAR (MAX)     NULL,
    [SiteId]                      INT                NULL,
    [Created]                     DATE               NOT NULL,
    [Deleted]                     BIT                DEFAULT ((0)) NOT NULL,
    [EmergencyContactId]          INT                NULL,
    [TRRBackgroundCheck]          BIT                CONSTRAINT [DF_AspNetUsers_TRRBackgroundCheck] DEFAULT ((0)) NOT NULL,
    [OtherBackgroundCheck]        BIT                CONSTRAINT [DF_AspNetUsers_OtherBackgroundCheck] DEFAULT ((0)) NOT NULL,
    [OtherBackgroundCheckComment] VARCHAR (MAX)      NULL,
    [CodeOfConductTraining]       BIT                CONSTRAINT [DF_AspNetUsers_CodeOfConductTraining] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_AspNetUsers_AspNetUsers_SponsoredById] FOREIGN KEY ([SponsoredById]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_AspNetUsers_Contacts_EmergencyContactId] FOREIGN KEY ([EmergencyContactId]) REFERENCES [dbo].[Contacts] ([Id]),
    CONSTRAINT [FK_AspNetUsers_EventSites_SiteId] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[EventSites] ([Id])
);

