CREATE TABLE [dbo].[CalendarEvents] (
    [Id]                 INT             IDENTITY (1, 1) NOT NULL,
    [Name]               NVARCHAR (MAX)  NULL,
    [Description]        NVARCHAR (MAX)  NULL,
    [EventTypeId]        INT             NOT NULL,
    [SiteId]             INT             NOT NULL,
    [GroupId]            INT             NOT NULL,
    [Date]               DATETIME2 (7)   NOT NULL,
    [StartTime]          INT             NOT NULL,
    [EndTime]            INT             NOT NULL,
    [CreatedById]        NVARCHAR (450)  NULL,
    [Created]            DATETIME2 (7)   NOT NULL,
    [ModifiedById]       NVARCHAR (450)  NULL,
    [Modified]           DATETIME2 (7)   NOT NULL,
    [Color]              NVARCHAR (MAX)  NULL,
    [Fee]                DECIMAL (18, 2) NOT NULL,
    [MaxCapacity]        INT             NOT NULL,
    [Attended]           INT             NOT NULL,
    [OldEventTypeId]     INT             NOT NULL,
    [OldEventSiteId]     INT             NOT NULL,
    [OldId]              INT             NOT NULL,
    [OldCreatedById]     INT             NOT NULL,
    [OldModifiedById]    INT             NOT NULL,
    [Deleted]            DATETIME2 (7)   NULL,
    [Canceled]           DATETIME2 (7)   NULL,
    [Report]             NVARCHAR (MAX)  NULL,
    [Status]             INT             NOT NULL,
    [OldEventCount]      INT             NOT NULL,
    [OldEventMultiOrder] INT             NOT NULL,
    [OldEventRepeat]     INT             NOT NULL,
    [ProjectedCost]      DECIMAL (18, 2) NOT NULL,
    [OldEventVisibility] NVARCHAR (1)    NOT NULL,
    CONSTRAINT [PK_CalendarEvents] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_CalendarEvents_AspNetUsers_CreatedById] FOREIGN KEY ([CreatedById]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_CalendarEvents_AspNetUsers_ModifiedById] FOREIGN KEY ([ModifiedById]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [FK_CalendarEvents_CalendarEventTypes_EventTypeId] FOREIGN KEY ([EventTypeId]) REFERENCES [dbo].[CalendarEventTypes] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_CalendarEvents_EventSites_SiteId] FOREIGN KEY ([SiteId]) REFERENCES [dbo].[EventSites] ([Id]) ON DELETE CASCADE
);

