CREATE TABLE [dbo].[EventSites] (
    [Id]                INT            IDENTITY (1, 1) NOT NULL,
    [Name]              NVARCHAR (MAX) NULL,
    [GroupId]           INT            NOT NULL,
    [GroupName]         NVARCHAR (MAX) NULL,
    [Description]       NVARCHAR (MAX) NULL,
    [MainId]            INT            NULL,
    [GOVTId]            INT            NULL,
    [CoordinatorId]     INT            NULL,
    [NationalId]        INT            NULL,
    [OutreachId]        INT            NULL,
    [Originated]        DATE           NULL,
    [SecurityClearance] NVARCHAR (MAX) NULL,
    [PoolRental]        BIT            NOT NULL,
    [TypeId]            INT            NOT NULL,
    [StaffTypeId]       INT            NOT NULL,
    [SiteGroupId]       INT            NOT NULL,
    [SiteStatusId]      INT            NOT NULL,
    [OldId]             INT            NOT NULL,
    [AllowEverybody]    BIT            DEFAULT ((0)) NOT NULL,
    [Deleted]           BIT            CONSTRAINT [DF_EventSites_Deleted] DEFAULT ((0)) NOT NULL,
    [RegionId]          INT            NULL,
    CONSTRAINT [PK_EventSites] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_EventSites_Contacts_CoordinatorId] FOREIGN KEY ([CoordinatorId]) REFERENCES [dbo].[Contacts] ([Id]),
    CONSTRAINT [FK_EventSites_Contacts_GOVTId] FOREIGN KEY ([GOVTId]) REFERENCES [dbo].[Contacts] ([Id]),
    CONSTRAINT [FK_EventSites_Contacts_MainId] FOREIGN KEY ([MainId]) REFERENCES [dbo].[Contacts] ([Id]),
    CONSTRAINT [FK_EventSites_Contacts_NationalId] FOREIGN KEY ([NationalId]) REFERENCES [dbo].[Contacts] ([Id]),
    CONSTRAINT [FK_EventSites_Contacts_OutreachId] FOREIGN KEY ([OutreachId]) REFERENCES [dbo].[Contacts] ([Id]),
    CONSTRAINT [FK_EventSites_Regions] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Regions] ([RegionId])
);

